### ISSUE TITLE
Maybe A Version Issue

### ISSUE THREAD

**Issue by a140262** [tripl-ai/docker#1]
I was trying to run an ARC job via AWS Batch service (ECS), it runs OK with arc_2.0.0_spark_2.4.3_scala_2.12_hadoop_2.9.2_1.2.0 but having the following error with a different scala version arc_2.0.0_spark_2.4.3_scala_2.11_hadoop_2.9.2_1.1.0:

Exception in thread "main" java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V

**Comment by seddonm1** [comment]
yes this looks to be a version issue. let me investigate

**Comment by seddonm1** [comment]
file looks ok can you please try the same release version: arc_2.0.0_spark_2.4.3_scala_2.11_hadoop_2.9.2_**1.2.0**

**Comment by seddonm1** [comment]
closed based on offline discussion confirming not related to arc.
